#! /bin/sh
# ~/.xinitrc
# #
# Executed by startx (run your window manager from here)

#if [ -d /etc/X11/xinit/xinitrc.d ]; then
#  for f in /etc/X11/xinit/xinitrc.d/*; do
#    [ -x "$f" ] && . "$f"
#  done
#  unset f
#fi

# Start a urxvt daemon
# With urxvt client launched from xmonad, attach to it
/usr/bin/urxvtd -q -f -o &

# Set some basic xorg settings
xcompmgr &
xsetroot -cursor_name left_ptr
setxkbmap -layout us -variant colemak
setxkbmap -option "" -layout "us(colemak),us,us(dvorak)" -option grp:alt_space_toggle

# Load Solarized Xresources
[[ -f ~/.Xresources ]] && xrdb -merge ~/.Xresources &

# Start several background programs
sh ~/.fehbg &
xmodmap ~/.Xmodmap &
{ sleep 2; /usr/bin/dropboxd; } &
{ sleep 2; /usr/bin/xflux -z 11229; } &
#{ sleep 2; /usr/bin/skype; } &

#{ sleep 10; /usr/bin/droidcam; } &
#{ sleep 2; /usr/bin/pavucontrol; } &
#{ sleep 10; /usr/bin/pasystray; } &
#{ sleep 10; /usr/bin/specto; } &
#{ sleep 2; /usr/bin/clipit; } &
#{ sleep 2; /usr/bin/remmina; } &
#{ sleep 10; /usr/bin/pidgin; } &
#{ sleep 10; /usr/bin/googsystray; } &
#{ sleep 2; /usr/bin/krusader; } &
#{ sleep 10; /usr/bin/weechat-curses; } &

# Window manager should always be the last thing run
exec xmonad
