#! /bin/sh
# ~/.xinitrc
# #
# Executed by startx (run your window manager from here)

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

if [ -f /etc/os-release ]; then
    NAME=$(grep "^NAME" /etc/os-release | awk -F = '{print $2}')
    case "$NAME" in
        "\"Arch Linux\"")
            # Start a urxvt daemon
            # With urxvt client launched from xmonad, attach to it
            /usr/bin/urxvtd -q -f -o &

            # Set some basic xorg settings
            /usr/bin/xcompmgr &
            /usr/bin/xsetroot -cursor_name left_ptr &
            /usr/bin/setxkbmap -layout us -variant colemak &
            /usr/bin/setxkbmap -option "" -layout "us(colemak),us,us(dvorak)" -option grp:alt_space_toggle &

            # Mouse control
            #xset m 7 10 &     # Very Fast
            #xset m 5 4 &     # Faster
            #xset m 3 10 &     # Normal(Fast)
            #xset m default &  # System Default
            #xset m 0 10 &     # Glacial
            #xset m <pixels to move when going fast> <pixels threshold before moving fast>
            # Read: http://linuxreviews.org/howtos/xfree/mouse_speed_in_x/
            /usr/bin/xset m 27/2 1 &

            # Load Solarized Xresources
            [[ -f ~/.Xresources ]] && /usr/bin/xrdb -merge ~/.Xresources &

            # Start several background programs
            /usr/bin/sh ~/.fehbg &
            /usr/bin/xmodmap ~/.Xmodmap &
            { sleep 2; /usr/bin/dropboxd; } &
            { sleep 2; /usr/bin/xflux -z 11229; } &
            #{ sleep 2; /usr/bin/skype; } &

            #{ sleep 10; /usr/bin/droidcam; } &
            #{ sleep 2; /usr/bin/pavucontrol; } &
            #{ sleep 10; /usr/bin/pasystray; } &
            #{ sleep 10; /usr/bin/specto; } &
            #{ sleep 2; /usr/bin/clipit; } &
            #{ sleep 2; /usr/bin/remmina; } &
            #{ sleep 10; /usr/bin/pidgin; } &
            #{ sleep 10; /usr/bin/googsystray; } &
            #{ sleep 2; /usr/bin/krusader; } &
            #{ sleep 10; /usr/bin/weechat-curses; } &

            # Window manager should always be the last thing run
            exec /usr/bin/xmonad
            ;;
        "\"elementary OS\"")
            exit 0
            ;;
        *)
            echo "No Linux distribution matched"
    esac
fi
