"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"""         vimrc Configuration
"""
"""     Author: Stanley Chan
"""     Github: https://github.com/Happy-Dude
"""
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

"""""""""""""""""""""""""""""""
"{ """      Preamble       """"
"""""""""""""""""""""""""""""""
set nocompatible        " Use Vim defaults
set modelines=0         " Set modelines to 0 to prevent several security exploits

" Home Manager supplies the composed runtime root; retain direct sourcing.
let s:vim_dir = get(g:, 'dotfiles_vim_runtime',
      \ fnamemodify(resolve(expand('<sfile>:p')), ':h')) . '/'
let s:vimrc_dir = s:vim_dir . 'vimrc_dir/'
let s:vimpack_settings_dir = s:vimrc_dir . 'packages/'

function! s:SourceConfig(name) abort
  execute 'source' fnameescape(s:vimrc_dir . a:name . '.vim')
endfunction

function! s:SourcePackageConfig(name) abort
  execute 'source' fnameescape(s:vimpack_settings_dir . a:name . '.vim')
endfunction

if has('nvim')
  " Disable unused providers and silence checkhealth warnings
  let g:loaded_node_provider = 0
  let g:loaded_perl_provider = 0
  let g:loaded_python3_provider = 0
  let g:loaded_ruby_provider = 0
else
  " Function keys that start with <Esc> are recognized in insert mode.
  set esckeys
endif
" }


"""""""""""""""""""""""""""""""
"{ """ Plugin Configuration """
"""""""""""""""""""""""""""""""

if &loadplugins

  if !has('nvim')
    call s:SourcePackageConfig('editorconfig')
    packadd! editorconfig
  endif

  " Load Home Manager native packages before configuring them.
  packloadall

  if has('nvim')
    " Register the CodeCompanion source before CoC scans autoload sources.
    lua require('codecompanion_nvim')
  endif

  " Use fzf when available; ctrlp remains the pure Vimscript fallback.
  if executable("fzf")
    call s:SourcePackageConfig('fzf')
  else
    call s:SourcePackageConfig('ctrlp')
  endif

  if executable("node")
    call s:SourcePackageConfig('coc')
  endif

  let s:package_configs = [
        \ 'ack',
        \ 'airline',
        \ 'dirvish',
        \ 'go',
        \ 'indent_guides',
        \ 'solarized',
        \ 'vimtex',
        \ ]

  if !has('nvim')
    call add(s:package_configs, 'rainbow')
  endif

  for s:package_config in s:package_configs
    call s:SourcePackageConfig(s:package_config)
  endfor
  unlet s:package_config
  unlet s:package_configs

  if has('nvim')
    " Configure Neovim plugins before filetype hooks can use their state.
    packadd! rustowl-nvim
    lua require('init')
  endif

  syntax enable               " Enable syntax highlighting
  filetype plugin indent on   " Enable filetype plugin and filetype-based indentation

endif
" }


for s:config in [
      \ "bell",
      \ "buffer",
      \ "cache",
      \ "clipboard",
      \ "colorscheme",
      \ "cpoptions",
      \ "cursorlinecolumn",
      \ "diff",
      \ "encoding",
      \ "folding",
      \ "formatoptions",
      \ "listchars",
      \ "match",
      \ "mouse",
      \ "search",
      \ "spellcheck",
      \ "statusline",
      \ "tabspaces",
      \ "visual",
      \ "wildmenu",
      \ "wordwrap",
      \ "mappings",
      \ "autocmds",
      \ "functions",
      \ ]
  call s:SourceConfig(s:config)
endfor
unlet s:config
