[dev]
source              = notmuch://~/.mail/
maildir-store       = ~/.mail/
query-map           = ~/.config/aerc/notmuch-map.conf
check-mail           = 10m
check-mail-cmd      = "mbsync lostsanctum && notmuch new"
check-mail-timeout  = 90s
default             = Unread
#source              = imaps://schan%40lostsanctum.dev@imap.migadu.com:993
outgoing            = smtps://schan%40lostsanctum.dev@smtp.migadu.com:465
#default             = INBOX
from                = "Stanley Chan" <schan@lostsanctum.dev>
copy-to             = Sent
cache-headers       = true
#source-cred-cmd     = "pass show email/aerc/schan@lostsanctum.dev"
outgoing-cred-cmd   = "pass show email/aerc/schan@lostsanctum.dev"
folders-sort        = linux-api,linux-bcachefs,linux-bpf,linux-cgroups,linux-debuggers,linux-io-uring,linux-netdev,linux-next,linux-perf-users,linux-rust,linux-security-module,linux-selinux,linux-toolchains,linux-trace-devel,linux-kernel-announce,INBOX,Unread,Drafts,Sent,Archive,Trash,Junk,ctlug,openbsd-tech,openbsd-announce,freebsd-security,freebsd-announce,dragonfly-commits,dragonfly-users,netbsd-tech-kern,netbsd-announce,ros-diffs,ros-announce,illumos-commits

