;; org-babel settings

(setq org-confirm-babel-evaluate nil
      org-src-fontify-natively t
      org-src-tab-acts-natively t)

;; ref: https://orgmode.org/manual/Languages.html
;; https://orgmode.org/worg/org-contrib/babel/languages.html
(org-babel-do-load-languages
 'org-babel-load-languages
 '(
   ;; Core
   ;(abc         . t)
   ;(asymptote   . t)
   (awk         . t)
   (C           . t)  ; enables C, C++, and D
   (calc        . t)
   ;(clojure     . t)
   ;(comint      . t)
   ;(coq         . t)
   (css         . t)
   ;(ditaa       . t)
   (dot         . t)
   ;(ebnf        . t)
   (emacs-lisp  . t)
   (eshell      . t)
   ;(forth       . t)
   ;(fortran     . t)
   ;(F90         . t)
   ;(gnuplot     . t)
   (haskell     . t)
   ;(io          . t)
   ;(J           . t)
   ;(java        . t)
   (js          . t)
   (latex       . t)
   (lua         . t)
   ;(ledger      . t)
   ;(ly          . t)
   (lisp        . t)
   (makefile    . t)
   ;(matlab      . t)
   ;(max         . t)
   (mscgen      . t)
   ;(ocaml       . t)
   ;(octave      . t)
   (org         . t)
   (perl        . t)
   ;(picolisp    . t)
   ;(plantuml    . t)
   ;(processing  . t)
   (python      . t)
   ;(R           . t)
   (ruby        . t)
   ;(sass        . t)
   ;(scala       . t)
   ;(scheme      . t)
   ;(screen      . t)
   (sed         . t)
   (shell       . t)
   ;(shen        . t)
   (sql         . t)
   (sqlite      . t)
   ;(stan        . t)
   ;(vala        . t)

   ;; Contributed
   ;(eukleides   . t)
   ;(fomus       . t)
   ;(groovy      . t)
   ;(julia       . t)
   ;(mathematica . t)
   ;(mathomatic  . t)
   ;(oz          . t)
   ;(stata       . t)
   ;(tcl         . t)

   ;; Emacs Package
   ;(axiom       . t)
   ;(browser     . t)
   ;(cypher      . t)
   ;(elixir      . t)
   ;(http        . t)
   ;(ipython     . t)
   ;(kotlin      . t)
   ;(lfe         . t)
   ;(mongo       . t)
   ;(prolog      . t)
   ;(rec         . t)
   ;(sml         . t)
   ;(translate   . t)
   ;(typescript  . t)
   ))
