{pkgs}: let
  perlWithLanguageServer = pkgs.perl.withPackages (ps: [ps.PerlLanguageServer]);
  treesitGrammars = pkgs.emacsPackages.treesit-grammars.with-grammars (grammars:
    with grammars; [
      tree-sitter-bash
      tree-sitter-c
      tree-sitter-clojure
      tree-sitter-cpp
      tree-sitter-css
      tree-sitter-fennel
      tree-sitter-fish
      tree-sitter-go
      tree-sitter-gomod
      tree-sitter-haskell
      tree-sitter-hcl
      tree-sitter-html
      tree-sitter-javascript
      tree-sitter-json
      tree-sitter-kotlin
      tree-sitter-latex
      tree-sitter-lua
      tree-sitter-markdown
      tree-sitter-markdown-inline
      tree-sitter-nix
      tree-sitter-perl
      tree-sitter-python
      tree-sitter-ruby
      tree-sitter-rust
      tree-sitter-sql
      # The locked TSX derivation exports tree_sitter_typescript instead of
      # tree_sitter_tsx, so Emacs cannot load it. web-mode remains the TSX mode.
      tree-sitter-typescript
      tree-sitter-typst
      tree-sitter-vim
      tree-sitter-yaml
      tree-sitter-zig
    ]);
in {
  packages = epkgs:
    with epkgs; [
      auctex
      clojure-mode
      company
      company-box
      fennel-mode
      fish-mode
      go-mode
      haskell-mode
      kotlin-mode
      lsp-mode
      lua-mode
      rust-mode
      terraform-mode
      treesit-auto
      typescript-mode
      typst-ts-mode
      vimrc-mode
      web-mode
      zig-mode
    ];

  # Nix owns only the store paths.  The Emacs Lisp that consumes them lives
  # in the native emacs/lsp-servers.el so it stays readable and editable as
  # ordinary Emacs Lisp.
  paths = pkgs.writeText "emacs-lsp-paths.el" ''
    ;;; lsp-paths.el --- Nix-owned store paths for lsp-servers.el -*- lexical-binding: t; -*-

    ;; Generated by emacs/lsp.nix.  Edit lsp-servers.el instead.

    (defconst dotfiles-lsp-treesit-grammars-path "${treesitGrammars}/lib")

    (defconst dotfiles-lsp-server-commands
      '((dotfiles-bash . ("${pkgs.bash-language-server}/bin/bash-language-server" "start"))
        (dotfiles-clangd . ("${pkgs.clang-tools}/bin/clangd"))
        (dotfiles-clojure . ("${pkgs.clojure-lsp}/bin/clojure-lsp" "listen"))
        (eslint . ("${pkgs.vscode-langservers-extracted}/bin/vscode-eslint-language-server" "--stdio"))
        (dotfiles-fennel . ("${pkgs.fennel-ls}/bin/fennel-ls" "--server"))
        (dotfiles-fish . ("${pkgs.fish-lsp}/bin/fish-lsp" "start"))
        (dotfiles-gopls . ("${pkgs.gopls}/bin/gopls"))
        (dotfiles-haskell . ("${pkgs.haskell-language-server}/bin/haskell-language-server-wrapper" "--lsp"))
        (dotfiles-json . ("${pkgs.vscode-langservers-extracted}/bin/vscode-json-language-server" "--stdio"))
        (dotfiles-kotlin . ("${pkgs.kotlin-language-server}/bin/kotlin-language-server"))
        (dotfiles-lua . ("${pkgs.lua-language-server}/bin/lua-language-server"))
        (dotfiles-marksman . ("${pkgs.marksman}/bin/marksman" "server"))
        (dotfiles-nixd . ("${pkgs.nixd}/bin/nixd"))
        (dotfiles-oxlint . ("${pkgs.oxlint}/bin/oxlint" "--lsp"))
        (dotfiles-perl-language-server . ("${perlWithLanguageServer}/bin/perl" "-MPerl::LanguageServer" "-e" "Perl::LanguageServer::run"))
        (dotfiles-perl-navigator . ("${pkgs.perlnavigator}/bin/perlnavigator" "--stdio"))
        (dotfiles-ruff . ("${pkgs.ruff}/bin/ruff" "server"))
        (dotfiles-rust-analyzer . ("${pkgs.rust-analyzer}/bin/rust-analyzer"))
        (dotfiles-terraform . ("${pkgs.terraform-ls}/bin/terraform-ls" "serve"))
        (dotfiles-texlab . ("${pkgs.texlab}/bin/texlab"))
        (dotfiles-tinymist . ("${pkgs.tinymist}/bin/tinymist" "lsp"))
        (dotfiles-typescript . ("${pkgs.typescript-language-server}/bin/typescript-language-server" "--stdio"))
        (dotfiles-vim . ("${pkgs.vim-language-server}/bin/vim-language-server" "--stdio"))
        (dotfiles-yaml . ("${pkgs.yaml-language-server}/bin/yaml-language-server" "--stdio"))
        (dotfiles-zls . ("${pkgs.zls}/bin/zls"))
        (dotfiles-zuban . ("${pkgs.zuban}/bin/zuban" "server"))))

    (defconst dotfiles-typescript-sdk
      "${pkgs.typescript}/lib/node_modules/typescript/lib/tsserver.js")

    (provide 'dotfiles-lsp-paths)
    ;;; lsp-paths.el ends here
  '';
}
