{pkgs}: let
  inherit
    (import ../lib/language-servers.nix {
      inherit pkgs;
      lib = pkgs.lib;
    })
    bin
    ;
  treesitGrammars = pkgs.emacsPackages.treesit-grammars.with-grammars (grammars:
    with grammars; [
      tree-sitter-bash
      tree-sitter-c
      tree-sitter-clojure
      tree-sitter-cpp
      tree-sitter-css
      tree-sitter-fennel
      tree-sitter-fish
      tree-sitter-go
      tree-sitter-gomod
      tree-sitter-haskell
      tree-sitter-hcl
      tree-sitter-html
      tree-sitter-javascript
      tree-sitter-json
      tree-sitter-kotlin
      tree-sitter-latex
      tree-sitter-lua
      tree-sitter-markdown
      tree-sitter-markdown-inline
      tree-sitter-nix
      tree-sitter-perl
      tree-sitter-python
      tree-sitter-ruby
      tree-sitter-rust
      tree-sitter-sql
      # The locked TSX derivation exports tree_sitter_typescript instead of
      # tree_sitter_tsx, so Emacs cannot load it. web-mode remains the TSX mode.
      tree-sitter-typescript
      tree-sitter-typst
      tree-sitter-vim
      tree-sitter-yaml
      tree-sitter-zig
    ]);
in {
  packages = epkgs:
    with epkgs; [
      auctex
      clojure-mode
      company
      company-box
      fennel-mode
      fish-mode
      go-mode
      haskell-mode
      kotlin-mode
      lsp-mode
      lua-mode
      rust-mode
      terraform-mode
      treesit-auto
      typescript-mode
      typst-ts-mode
      vimrc-mode
      web-mode
      zig-mode
    ];

  # Nix owns only the store paths.  The Emacs Lisp that consumes them lives
  # in the native emacs/lsp-servers.el so it stays readable and editable as
  # ordinary Emacs Lisp.
  paths = pkgs.writeText "emacs-lsp-paths.el" ''
    ;;; lsp-paths.el --- Nix-owned store paths for lsp-servers.el -*- lexical-binding: t; -*-

    ;; Generated by emacs/lsp.nix.  Edit lsp-servers.el instead.

    (defconst dotfiles-lsp-treesit-grammars-path "${treesitGrammars}/lib")

    (defconst dotfiles-lsp-server-commands
      '((dotfiles-bash . ("${bin "bash-language-server"}" "start"))
        (dotfiles-clangd . ("${bin "clangd"}"))
        (dotfiles-clojure . ("${bin "clojure-lsp"}" "listen"))
        (eslint . ("${bin "vscode-eslint-language-server"}" "--stdio"))
        (dotfiles-fennel . ("${bin "fennel-ls"}" "--server"))
        (dotfiles-fish . ("${bin "fish-lsp"}" "start"))
        (dotfiles-gopls . ("${bin "gopls"}"))
        (dotfiles-haskell . ("${bin "haskell-language-server"}" "--lsp"))
        (dotfiles-json . ("${bin "vscode-json-language-server"}" "--stdio"))
        (dotfiles-kotlin . ("${bin "kotlin-language-server"}"))
        (dotfiles-lua . ("${bin "lua-language-server"}"))
        (dotfiles-marksman . ("${bin "marksman"}" "server"))
        (dotfiles-nixd . ("${bin "nixd"}"))
        (dotfiles-oxlint . ("${bin "oxlint"}" "--lsp"))
        (dotfiles-perl-language-server . ("${bin "perl-language-server"}" "-MPerl::LanguageServer" "-e" "Perl::LanguageServer::run"))
        (dotfiles-perl-navigator . ("${bin "perlnavigator"}" "--stdio"))
        (dotfiles-ruff . ("${bin "ruff"}" "server"))
        (dotfiles-rust-analyzer . ("${bin "rust-analyzer"}"))
        (dotfiles-terraform . ("${bin "terraform-ls"}" "serve"))
        (dotfiles-texlab . ("${bin "texlab"}"))
        (dotfiles-tinymist . ("${bin "tinymist"}" "lsp"))
        ;; typescript 7 (tsgo) ships no tsserver.js; tsgo serves LSP
        ;; directly over stdio, so there is no SDK pin.
        (dotfiles-typescript . ("${bin "tsgo"}" "--lsp" "--stdio"))
        (dotfiles-vim . ("${bin "vim-language-server"}" "--stdio"))
        (dotfiles-yaml . ("${bin "yaml-language-server"}" "--stdio"))
        (dotfiles-zls . ("${bin "zls"}"))
        (dotfiles-zuban . ("${bin "zuban"}" "server"))))

    (provide 'dotfiles-lsp-paths)
    ;;; lsp-paths.el ends here
  '';
}
